name: base
channels:
  - conda-forge
  - defaults
dependencies:
  # Python
  - natsort ==7.0.1
  - pandas ==1.2.4
  - seaborn ==0.11.2
  - xarray ==0.15.1
  - pyyaml ==5.4.1
  - pip:
    - esgf-pyclient ==0.3.1
