name: Update

on:
  workflow_dispatch:

  push:
    branches: [ main ]
    paths:
      - CMIP6_downscaling_plans.csv
  pull_request:
    branches: [ main ]
    paths:
      - CMIP6_downscaling_plans.csv

jobs:
  update-tables:

    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Setup mamba
      uses: conda-incubator/setup-miniconda@v2
      with:
        environment-file: environment.yml
        miniforge-version: latest

    - name: Update tables
      run: |
        which -a python
        conda activate test
        make update
       
    - name: Commit
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git commit -am "[Actions] Update"
        git push
