name: Update

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      
    - name: Update tables
      run: make update
       
    - name: Commit
      run: |
        git config --global user.name 'Actions'
        git config --global user.email 'jesusff@users.noreply.github.com'
        git commit -am "[Actions] Update"
        git push
